name: CI/CD Pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest

    - name: Build Docker image
      run: |
        docker build -t rickmorty-api api/
        eval $(minikube -p minikube docker-env)
        docker build -t rickmorty-api api/

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f yamls/
        sleep 30

    - name: Run tests
      run: |
        minikube service list
        kubectl get pods
        kubectl port-forward svc/rickmorty-api-service 8080:80 &
        sleep 5
        curl -f http://localhost:8080/healthcheck
        curl -f http://localhost:8080/robots
